version: '3'

services:

## JSON Server
  json-server:
    build:
      context: ./dockerfile
      dockerfile: json-server.Dockerfile
    container_name: json-server
    hostname: json-server
    image: mock/json-server:latest
    volumes:
      - ./volumes/json-server:/data
    tty: true
    ports:
      - "9100:3000"
      - "9101:3001"
      - "9102:3002"
    restart: unless-stopped

## Wiremock
  wiremock:
    build:
      context: ./dockerfile
      dockerfile: wiremock.Dockerfile
    container_name: wiremock
    hostname: wiremock
    image: mock/wiremock:latest
    volumes:
      - ./volumes/wiremock:/home/wiremock
    tty: true
    ports:
      - "9110:8080"
    restart: unless-stopped

## Mockserver
  mockserver:
    build:
      context: ./dockerfile
      dockerfile: mockserver.Dockerfile
    container_name: mockserver
    hostname: mockserver
    image: mock/mockserver:latest
    volumes:
      - ./volumes/mockserver:/config
    environment:
      MOCKSERVER_LOG_LEVEL: TRACE
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    tty: true
    ports:
      - "9120:1080"
    restart: unless-stopped
